#' Reduce spatial and temporal sampling bias
#'
#' @param occ_data Data frame. Species occurrence records. Must contain columns:
#'   "Species", "x", "y", "year", "month", "day".
#' @param bias_result "BiasCheckResult" object. The result object returned by
#'   [bias_check()].
#' @param min_dist_km Numeric. Minimum distance (in kilometres) used in
#'   [spThin::thin()] for spatial thinning.
#' @param thin_reps Integer. Number of replicate thinning runs.
#' @param temporal_level Character. Temporal level used to address temporal
#'   sampling bias. Must be one of "month", "quarter", or "season".
#' @param seed Integer. Random seed for reproducibility of thinning and
#'   subsampling steps.
#'
#' @return A data frame (the same type as "occ_data") after spatial thinning
#'   and optional temporal balancing. The returned object has an attribute
#'   "thinning_info" containing detailed thinning statistics.
#' @examples
#' \donttest{
#' occ_thinned<-bias_reduce(occ_data=occ_ob2,
#' bias_result=bias_test,
#' min_dist_km = 56,
#' thin_reps = 30,
#' temporal_level = "quarter",
#' seed = 123)
#' }
#' @export
bias_reduce <- function(occ_data,
                        bias_result,
                        min_dist_km = 56,
                        thin_reps = 10,
                        temporal_level = "quarter",
                        seed = 123) {

  # Set random seed
  set.seed(seed)

  # 2. Validate input data
  required_cols <- c("Species", "x", "y", "year", "month", "day", temporal_level)
  if (!all(required_cols %in% colnames(occ_data))) {
    missing_cols <- setdiff(required_cols, colnames(occ_data))
    stop(paste("Missing required columns:", paste(missing_cols, collapse = ", ")))
  }

  if (!inherits(bias_result, "BiasCheckResult")) {
    stop("bias_result must be a BiasCheckResult object generated by bias_check()")
  }

  # 3. Add quarter and season variables if not present
  if (!"quarter" %in% colnames(occ_data)) {
    occ_data <- occ_data |>
      dplyr::mutate(
        quarter = dplyr::case_when(
          month %in% 1:3 ~ "Q1",
          month %in% 4:6 ~ "Q2",
          month %in% 7:9 ~ "Q3",
          month %in% 10:12 ~ "Q4",
          TRUE ~ NA_character_
        )) |>
      dplyr::filter(!is.na(quarter))
  }

  if (!"season" %in% colnames(occ_data)) {
    get_season <- function(month) {
      dplyr::case_when(
        month %in% 3:5 ~ "Spring",
        month %in% 6:8 ~ "Summer",
        month %in% 9:11 ~ "Fall",
        TRUE ~ "Winter"
      )
    }
    occ_data$season <- get_season(occ_data$month)
  }

  # 4. Check temporal bias test results
  temporal_bias_p <- NA
  if ("Temporal_bias" %in% names(bias_result$Statistical_tests)) {
    temporal_test <- bias_result$Statistical_tests[["Temporal_bias"]]
    temporal_bias_p <- temporal_test$p_value
    message(paste("Temporal bias test p-value:", round(temporal_bias_p, 4)))
  } else {
    warning("Temporal bias test results not found")
  }

  # 5. Step 1: Spatial thinning (by quarter)
  message("\n=== Step 1: Spatial thinning ===")

  # Get all quarters
  quarters <- unique(occ_data$quarter)
  quarters <- sort(quarters[!is.na(quarters)])

  # Store thinned data per quarter
  quarter_thinned_data <- list()
  quarter_thinned_counts <- numeric(length(quarters))
  names(quarter_thinned_counts) <- quarters

  # Process each quarter
  for (i in seq_along(quarters)) {
    q <- quarters[i]
    quarter_data <- occ_data[occ_data$quarter == q, ]
    if (nrow(quarter_data) == 0) {
      message(paste("Quarter", q, ": no data, skipping"))
      quarter_thinned_data[[i]] <- quarter_data
      quarter_thinned_counts[i] <- 0
      next
    }

    # Check if spatial bias test exists for this quarter
    spatial_test_name <- paste0("Spatial_bias_", temporal_level, "_", q)
    spatial_test <- bias_result$Statistical_tests[[spatial_test_name]]

    if (!is.null(spatial_test)) {
      spatial_p <- spatial_test$p_value
      message(paste("Quarter", q, "spatial bias p-value:", round(spatial_p, 4)))

      # If spatial bias exists (p < 0.05), perform thinning
      if (!is.na(spatial_p) && spatial_p < 0.05) {
        message(paste("Quarter", q, "has spatial bias, performing thinning..."))
        if (nrow(quarter_data) <= 1) {
          # Original code had "return(quarter_data)" which would exit function - likely a bug.
          # We'll just keep the data as is and continue.
          quarter_thinned_data[[i]] <- quarter_data
          quarter_thinned_counts[i] <- nrow(quarter_data)
          next
        }

        thin_data <- data.frame(LAT = quarter_data$y, LONG = quarter_data$x,
                                SPECIES = quarter_data$Species, DATE = quarter_data$date)
        thinned_result <- spThin::thin(loc.data = thin_data, lat.col = "LAT", long.col = "LONG",
                                       spec.col = "SPECIES", thin.par = min_dist_km, reps = thin_reps,
                                       locs.thinned.list.return = TRUE, write.files = FALSE,
                                       write.log.file = FALSE, verbose = FALSE)
        thinned_coords <- thinned_result[[which.max(sapply(thinned_result, nrow))]]
        thinned_indices <- which(paste(thin_data$LAT, thin_data$LONG) %in%
                                   paste(thinned_coords$Lat, thinned_coords$Long))
        quarter_thinned_data[[i]] <- quarter_data[thinned_indices, ]
        quarter_thinned_counts[i] <- nrow(quarter_thinned_data[[i]])
        message(paste("Quarter", q, "thinning completed. Original points:", nrow(quarter_data)))
        message(paste("Points after thinning:", quarter_thinned_counts[i]))
      } else {
        # No spatial bias, keep all points
        warning(paste("Quarter", q, "has no spatial bias test result, keeping all data points"))
        quarter_thinned_data[[i]] <- quarter_data
        quarter_thinned_counts[i] <- nrow(quarter_data)
      }
    } else {
      # No test result, keep all points
      quarter_thinned_data[[i]] <- quarter_data
      quarter_thinned_counts[i] <- nrow(quarter_data)
    }
  }

  # Combine thinned data from all quarters
  spatial_thinned_data <- do.call(rbind, quarter_thinned_data)

  # 6. Step 2: Temporal balancing (if temporal bias exists)
  message("\n=== Step 2: Temporal balancing ===")
  final_thinned_data <- spatial_thinned_data

  if (!is.na(temporal_bias_p) && temporal_bias_p < 0.05) {
    message("Temporal bias detected, performing temporal balancing...")

    # Find quarter with smallest sample size
    min_count <- min(quarter_thinned_counts)
    min_quarter <- names(quarter_thinned_counts)[which.min(quarter_thinned_counts)]
    message(paste("Quarter with smallest sample size:", min_quarter, "sample size:", min_count))

    # Randomly sample other quarters to match the smallest size
    balanced_data_list <- list()
    for (i in seq_along(quarters)) {
      q <- quarters[i]
      q_name <- q
      q_data <- spatial_thinned_data[spatial_thinned_data$quarter == q, ]
      if (nrow(q_data) > 0) {
        if (quarter_thinned_counts[q_name] > min_count) {
          set.seed(seed)  # use same seed for reproducibility
          sampled_indices <- sample(1:nrow(q_data), size = min_count, replace = FALSE)
          balanced_q_data <- q_data[sampled_indices, ]
          message(paste("Quarter", q, "sampled from", nrow(q_data), "points to", nrow(balanced_q_data), "points"))
        } else {
          balanced_q_data <- q_data
          message(paste("Quarter", q, "keeping", nrow(balanced_q_data), "points"))
        }
        balanced_data_list[[i]] <- balanced_q_data
      } else {
        balanced_data_list[[i]] <- q_data
      }
    }

    # Combine balanced data
    final_thinned_data <- do.call(rbind, balanced_data_list)

    # Verify balancing results
    final_counts <- table(final_thinned_data$quarter)
    message("\nSample sizes per quarter after balancing:")
    for (q in names(final_counts)) {
      message(paste("Quarter", q, ":", final_counts[q]))
    }
  } else {
    message("No significant temporal bias, skipping temporal balancing")
  }

  # 7. Output thinning summary statistics
  message("\n=== Thinning summary ===")
  message(paste("Original total sample size:", nrow(occ_data)))
  message(paste("Sample size after spatial thinning:", nrow(spatial_thinned_data)))
  message(paste("Final sample size:", nrow(final_thinned_data)))
  message(paste("Retention ratio:", round(nrow(final_thinned_data) / nrow(occ_data) * 100, 2), "%"))

  # Retention ratio per quarter
  orig_counts <- table(occ_data$quarter)
  final_counts <- table(final_thinned_data$quarter)
  message("\nRetention ratio per quarter:")
  for (q in names(orig_counts)) {
    orig_q <- orig_counts[q]
    final_q <- ifelse(q %in% names(final_counts), final_counts[q], 0)
    ratio <- ifelse(orig_q > 0, round(final_q / orig_q * 100, 2), 0)
    message(paste("Quarter", q, ": ", orig_q, " -> ", final_q, " (", ratio, "%)"))
  }

  # 8. Add thinning information as attribute
  attr(final_thinned_data, "thinning_info") <- list(
    original_n = nrow(occ_data),
    spatial_thinned_n = nrow(spatial_thinned_data),
    final_n = nrow(final_thinned_data),
    min_dist_km = min_dist_km,
    thin_reps = thin_reps,
    temporal_bias_p = temporal_bias_p,
    quarter_counts_original = as.list(orig_counts),
    quarter_counts_final = as.list(final_counts),
    thinning_date = Sys.time()
  )

  return(final_thinned_data)
}
